# This Makefile was generated by the made script:
# https://github.com/alx741/made
#
# Replace FILE with your C code filename
# Replace PARTNO with the target chip model
#
# Dependencies:
#	SDCC


MMCU=stm8

CFLAGS =
CFLAGS += --std-sdcc11
CFLAGS += -l$(MMCU)
CFLAGS += -m$(MMCU)

INPUTS = $(shell find . -type f -name "*.c")
RELS := ${INPUTS:.c=.rel}
OUTPUT = stm8s.lib

$(OUTPUT): $(RELS)
	sdar -rc $@ $(RELS)

%.rel: %.c
	sdcc $(CFLAGS) -c $< -o $@

clean:
	rm -f ${RELS:.rel=.map} ${RELS:.rel=.rst} ${RELS:.rel=.cdb} ${RELS:.rel=.asm} ${RELS:.rel=.lst} ${RELS:.rel=.sym} $(RELS) $(OUTPUT)
